services:
  - type: web
    name: breast-cancer-mlops
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn deploy.app:app --host 0.0.0.0 --port 10000
    autoDeploy: true
